[package]
name = "nvr-db"
version = "0.1.0"
edition = "2024"

[dependencies]
turso = "0.4"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
rust-embed = "8"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
